;this file for FamiTone2 library generated by text2data tool

songs_music_data:
	.byte 4
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,307,256

@instruments:
	.byte $b0 ;instrument $00
	.word @env1,@env11,@env12
	.byte $00
	.byte $b0 ;instrument $01
	.word @env8,@env0,@env0
	.byte $00
	.byte $30 ;instrument $03
	.word @env2,@env0,@env0
	.byte $00
	.byte $30 ;instrument $04
	.word @env3,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $05
	.word @env8,@env0,@env12
	.byte $00
	.byte $30 ;instrument $06
	.word @env4,@env0,@env0
	.byte $00
	.byte $30 ;instrument $08
	.word @env5,@env0,@env0
	.byte $00
	.byte $30 ;instrument $09
	.word @env6,@env0,@env0
	.byte $00
	.byte $30 ;instrument $0a
	.word @env7,@env0,@env13
	.byte $00
	.byte $30 ;instrument $14
	.word @env7,@env0,@env0
	.byte $00
	.byte $30 ;instrument $19
	.word @env9,@env0,@env14
	.byte $00
	.byte $30 ;instrument $1a
	.word @env10,@env0,@env15
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cc,$cc,$cb,$03,$ca,$02,$c9,$02,$c8,$03,$c7,$04,$c6,$04,$c5,$04
	.byte $c4,$06,$c3,$04,$c2,$05,$c1,$05,$c0,$00,$18
@env2:
	.byte $cf,$ca,$c7,$c4,$c3,$c2,$c1,$c0,$00,$07
@env3:
	.byte $c8,$c6,$c4,$c2,$c2,$c1,$c1,$c0,$00,$07
@env4:
	.byte $c8,$02,$c7,$03,$c6,$02,$c5,$05,$c4,$02,$c3,$07,$c2,$0a,$c1,$0e
	.byte $c0,$00,$10
@env5:
	.byte $c8,$c7,$c6,$c5,$c4,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$00,$0c
@env6:
	.byte $c1,$c1,$c2,$c2,$c3,$c3,$c4,$00,$06
@env7:
	.byte $c4,$00,$00
@env8:
	.byte $c8,$00,$00
@env9:
	.byte $cf,$c9,$c6,$c3,$c0,$00,$04
@env10:
	.byte $cf,$cb,$c8,$c6,$c4,$c3,$c2,$c1,$c1,$c0,$00,$09
@env11:
	.byte $d8,$02,$d3,$02,$d0,$02,$cc,$02,$c7,$02,$c4,$02,$c0,$02,$c4,$02
	.byte $c7,$02,$cc,$02,$d0,$02,$d3,$d3,$d3,$00,$00
@env12:
	.byte $c0,$02,$c6,$00,$02
@env13:
	.byte $ba,$b7,$b7,$ba,$c0,$c6,$c9,$c9,$c6,$c0,$00,$00
@env14:
	.byte $ff,$00,$00
@env15:
	.byte $d5,$00,$00


@song0ch0:
@song0ch0loop:
@ref0:
	.byte $8e,$36,$91
@ref1:
	.byte $93
@ref2:
	.byte $93
@ref3:
	.byte $90,$36,$91
@ref4:
	.byte $93
@ref5:
	.byte $93
@ref6:
	.byte $8e,$36,$91
@ref7:
	.byte $93
@ref8:
	.byte $93
@ref9:
	.byte $90,$36,$91
@ref10:
	.byte $93
@ref11:
	.byte $93
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref12:
	.byte $81,$8e,$2e,$8f
@ref13:
	.byte $93
@ref14:
	.byte $93
@ref15:
	.byte $90,$2e,$91
@ref16:
	.byte $93
@ref17:
	.byte $93
@ref18:
	.byte $81,$8e,$2e,$8f
@ref19:
	.byte $93
@ref20:
	.byte $93
@ref21:
	.byte $90,$2e,$91
@ref22:
	.byte $93
@ref23:
	.byte $93
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref24:
	.byte $94,$3e,$82,$28,$8f
@ref25:
	.byte $83,$88,$28,$87,$00,$94,$3e,$82,$28
@ref26:
	.byte $87,$00,$89
@ref27:
	.byte $94,$3e,$82,$28,$85,$00,$94,$3e,$82,$28,$83
@ref28:
	.byte $83,$88,$28,$87,$00,$94,$3e,$82,$1e
@ref29:
	.byte $87,$88,$1e,$87,$00
	.byte $ff,$03
	.word @ref24
	.byte $ff,$06
	.word @ref25
@ref32:
	.byte $87,$00,$89
	.byte $ff,$07
	.word @ref27
	.byte $ff,$06
	.word @ref28
	.byte $ff,$04
	.word @ref29
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref36:
	.byte $8a,$12,$91
@ref37:
	.byte $8d,$00,$8c,$18,$81
@ref38:
	.byte $87,$86,$1e,$89
@ref39:
	.byte $1e,$89,$84,$1e,$85
@ref40:
	.byte $83,$86,$1e,$89,$8c,$18,$81
@ref41:
	.byte $87,$86,$1e,$83,$84,$1e,$83
@ref42:
	.byte $8a,$12,$91
	.byte $ff,$04
	.word @ref37
@ref44:
	.byte $87,$86,$1e,$89
	.byte $ff,$04
	.word @ref39
	.byte $ff,$05
	.word @ref40
	.byte $ff,$05
	.word @ref41
	.byte $fd
	.word @song0ch3loop

@song0ch4:
	.byte $fb,$01
@song0ch4loop:
@ref48:
	.byte $81,$fb,$01,$81,$fb,$02,$81,$fb,$01,$81,$fb,$02,$81,$fb,$01,$81
	.byte $fb,$02,$81,$fb,$01,$81,$fb,$02,$81,$fb,$01,$81
@ref49:
	.byte $fb,$02,$81,$fb,$01,$81,$fb,$02,$81,$fb,$01,$81,$fb,$02,$81,$fb
	.byte $01,$81,$fb,$02,$81,$fb,$01,$81,$fb,$02,$81,$fb,$01,$81
	.byte $ff,$0a
	.word @ref49
@ref51:
	.byte $83,$fb,$02,$81,$fb,$01,$81,$fb,$02,$81,$fb,$01,$81,$fb,$02,$81
	.byte $fb,$01,$81,$fb,$02,$81,$fb,$01,$81
	.byte $ff,$0a
	.word @ref49
	.byte $ff,$0a
	.word @ref49
	.byte $ff,$09
	.word @ref51
	.byte $ff,$0a
	.word @ref49
	.byte $ff,$0a
	.word @ref49
	.byte $ff,$09
	.word @ref51
	.byte $ff,$0a
	.word @ref49
	.byte $ff,$0a
	.word @ref49
	.byte $fd
	.word @song0ch4loop


@song1ch0:
@song1ch0loop:
@ref60:
	.byte $8f
@ref61:
	.byte $8f
@ref62:
	.byte $8f
@ref63:
	.byte $8f
@ref64:
	.byte $92,$12,$83,$00,$12,$83,$00,$0e,$83,$00,$08,$83,$00
@ref65:
	.byte $0e,$83,$00,$12,$83,$00,$87,$80,$44,$85
@ref66:
	.byte $85,$00,$92,$12,$83,$00,$0e,$83,$00,$08,$83,$00
@ref67:
	.byte $0e,$83,$00,$12,$83,$00,$87,$80,$48,$85
	.byte $ff,$0b
	.word @ref66
@ref69:
	.byte $0e,$83,$00,$12,$83,$00,$87,$04,$85
@ref70:
	.byte $85,$00,$0e,$83,$00,$12,$83,$00,$08,$85
@ref71:
	.byte $85,$00,$10,$83,$00,$12,$83,$00,$2a,$83,$00
@ref72:
	.byte $9f
@ref73:
	.byte $9f
@ref74:
	.byte $9f
@ref75:
	.byte $9f
@ref76:
	.byte $9f
@ref77:
	.byte $9f
@ref78:
	.byte $9f
@ref79:
	.byte $9f
@ref80:
	.byte $9f
@ref81:
	.byte $9f
@ref82:
	.byte $9f
@ref83:
	.byte $9f
	.byte $fd
	.word @song1ch0loop

@song1ch1:
	.byte $fb,$04
@song1ch1loop:
@ref84:
	.byte $fb,$01,$8f
@ref85:
	.byte $8f
@ref86:
	.byte $8f
@ref87:
	.byte $8f
@ref88:
	.byte $fb,$03,$81,$fb,$02,$85,$fb,$03,$81,$fb,$02,$85,$fb,$03,$81,$fb
	.byte $02,$85,$fb,$03,$81,$fb,$02,$85
	.byte $ff,$08
	.word @ref88
	.byte $ff,$08
	.word @ref88
	.byte $ff,$08
	.word @ref88
	.byte $ff,$08
	.word @ref88
	.byte $ff,$08
	.word @ref88
	.byte $ff,$08
	.word @ref88
	.byte $ff,$08
	.word @ref88
@ref96:
	.byte $9f
@ref97:
	.byte $9f
@ref98:
	.byte $9f
@ref99:
	.byte $9f
@ref100:
	.byte $9f
@ref101:
	.byte $9f
@ref102:
	.byte $9f
@ref103:
	.byte $9f
@ref104:
	.byte $9f
@ref105:
	.byte $9f
@ref106:
	.byte $9f
@ref107:
	.byte $9f
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@song1ch2loop:
@ref108:
	.byte $8f
@ref109:
	.byte $8f
@ref110:
	.byte $8f
@ref111:
	.byte $8f
@ref112:
	.byte $94,$3e,$92,$2a,$83,$94,$3e,$92,$2b,$00,$96,$46,$92,$27,$00,$20
	.byte $83,$00
@ref113:
	.byte $94,$3e,$92,$27,$00,$94,$3e,$92,$2b,$00,$96,$46,$01,$00,$94,$3e
	.byte $92,$16,$83
@ref114:
	.byte $85,$00,$94,$3e,$92,$2b,$00,$96,$46,$92,$27,$00,$20,$83,$00
@ref115:
	.byte $94,$3e,$92,$27,$00,$94,$3e,$92,$2b,$00,$96,$46,$01,$00,$94,$3e
	.byte $92,$18,$83
	.byte $ff,$0b
	.word @ref114
@ref117:
	.byte $94,$3e,$92,$27,$00,$94,$3e,$92,$2b,$00,$96,$46,$01,$00,$94,$3e
	.byte $92,$1c,$83
@ref118:
	.byte $85,$00,$94,$3e,$92,$27,$00,$96,$46,$92,$2b,$00,$94,$3e,$92,$20
	.byte $83
@ref119:
	.byte $85,$00,$96,$46,$92,$29,$00,$96,$46,$92,$2b,$00,$94,$3e,$92,$43
	.byte $00
@ref120:
	.byte $9f
@ref121:
	.byte $9f
@ref122:
	.byte $9f
@ref123:
	.byte $9f
@ref124:
	.byte $9f
@ref125:
	.byte $9f
@ref126:
	.byte $9f
@ref127:
	.byte $9f
@ref128:
	.byte $9f
@ref129:
	.byte $9f
@ref130:
	.byte $9f
@ref131:
	.byte $9f
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@song1ch3loop:
@ref132:
	.byte $8f
@ref133:
	.byte $8f
@ref134:
	.byte $8f
@ref135:
	.byte $8f
@ref136:
	.byte $8a,$12,$95,$86,$1f,$1a,$81
@ref137:
	.byte $84,$1e,$85,$86,$1e,$85,$84,$08,$85,$86,$1e,$85
	.byte $ff,$08
	.word @ref137
	.byte $ff,$08
	.word @ref137
@ref140:
	.byte $84,$1e,$85,$86,$1e,$85,$84,$08,$85,$86,$1f,$1a,$81
	.byte $ff,$08
	.word @ref137
	.byte $ff,$08
	.word @ref137
@ref143:
	.byte $84,$1e,$85,$08,$85,$08,$85,$86,$1e,$85
@ref144:
	.byte $9f
@ref145:
	.byte $9f
@ref146:
	.byte $9f
@ref147:
	.byte $9f
@ref148:
	.byte $9f
@ref149:
	.byte $9f
@ref150:
	.byte $9f
@ref151:
	.byte $9f
@ref152:
	.byte $9f
@ref153:
	.byte $9f
@ref154:
	.byte $9f
@ref155:
	.byte $9f
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref156:
	.byte $8f
@ref157:
	.byte $8f
@ref158:
	.byte $8f
@ref159:
	.byte $8f
@ref160:
	.byte $9f
@ref161:
	.byte $9f
@ref162:
	.byte $9f
@ref163:
	.byte $9f
@ref164:
	.byte $9f
@ref165:
	.byte $9f
@ref166:
	.byte $9f
@ref167:
	.byte $9f
@ref168:
	.byte $9f
@ref169:
	.byte $9f
@ref170:
	.byte $9f
@ref171:
	.byte $9f
@ref172:
	.byte $9f
@ref173:
	.byte $9f
@ref174:
	.byte $9f
@ref175:
	.byte $9f
@ref176:
	.byte $9f
@ref177:
	.byte $9f
@ref178:
	.byte $9f
@ref179:
	.byte $9f
	.byte $fd
	.word @song1ch4loop


@song2ch0:
	.byte $fb,$06
@song2ch0loop:
@ref180:
	.byte $f9,$85
	.byte $fd
	.word @song2ch0loop

@song2ch1:
@song2ch1loop:
@ref181:
	.byte $f9,$85
	.byte $fd
	.word @song2ch1loop

@song2ch2:
@song2ch2loop:
@ref182:
	.byte $f9,$85
	.byte $fd
	.word @song2ch2loop

@song2ch3:
@song2ch3loop:
@ref183:
	.byte $f9,$85
	.byte $fd
	.word @song2ch3loop

@song2ch4:
@song2ch4loop:
@ref184:
	.byte $f9,$85
	.byte $fd
	.word @song2ch4loop


@song3ch0:
	.byte $fb,$06
@song3ch0loop:
@ref185:
	.byte $f9,$85
	.byte $fd
	.word @song3ch0loop

@song3ch1:
@song3ch1loop:
@ref186:
	.byte $f9,$85
	.byte $fd
	.word @song3ch1loop

@song3ch2:
@song3ch2loop:
@ref187:
	.byte $f9,$85
	.byte $fd
	.word @song3ch2loop

@song3ch3:
@song3ch3loop:
@ref188:
	.byte $f9,$85
	.byte $fd
	.word @song3ch3loop

@song3ch4:
@song3ch4loop:
@ref189:
	.byte $f9,$85
	.byte $fd
	.word @song3ch4loop
