/*

		beep_SFX

		Sound Effect File.
		
		Info:
			Length			:	3
			Priority		:	0
			Channels used	:	Duty channel 2
		
		This file was generated by hammer2cbt

	*/
	#ifndef __beep_SFX_h_INCLUDE
#define __beep_SFX_h_INCLUDE
#define CBTFX_PLAY_beep_SFX CBTFX_init(&beep_SFX[0])
extern const unsigned char beep_SFX[];
#endif