/*

		beep_SFX

		Sound Effect File.
		
		Info:
			Length			:	3
			Priority		:	0
			Channels used	:	Duty channel 2
		
		This file was generated by hammer2cbt

	*/
#pragma bank 5
	const unsigned char beep_SFX[] = {
192, // Header
3,
0, 34, 128, 80, 231, 134, 0, 34, 128, 80, 89, 135, 0, 34, 128, 16, 231, 134
};