/*

	block_land_sfx

	Sound Effect File.

	Info:
		Length			:	7
		Bank			:	0
		Priority		:	0
		Channels used	:	Noise channel

	This file was generated by hammer2cbt

*/
#pragma bank 5
#define block_land_sfx_Length 7
#define block_land_sfx_Bank 0
#define block_land_sfx_CH_Used 15
#define block_land_sfx_Priority 0
#define CBTFX_PLAY_block_land_sfx CBTFX_init(&block_land_sfx[0][0], 7, 0, 15)
#include "cbtfx.h"

const unsigned char block_land_sfx[7][CBTFX_LENGTH] = {
	CBTFX_FRAME(2, 0, 0, 0, FX_E_3, 17, 15, 241),
	CBTFX_FRAME(1, 0, 0, 0, FX_E_3, 17, 13, 65),
	CBTFX_FRAME(1, 0, 0, 0, FX_E_3, 17, 11, 98),
	CBTFX_FRAME(3, 0, 0, 0, FX_E_3, 17, 7, 98),
	CBTFX_FRAME(2, 0, 0, 0, FX_E_3, 17, 3, 98),
	CBTFX_FRAME(1, 0, 0, 0, FX_E_3, 17, 1, 98)
};