/*

		blockLand_SFX

		Sound Effect File.
		
		Info:
			Length			:	6
			Priority		:	0
			Channels used	:	Noise channel
		
		This file was generated by hammer2cbt

	*/
	#ifndef __blockLand_SFX_h_INCLUDE
#define __blockLand_SFX_h_INCLUDE
#define CBTFX_PLAY_blockLand_SFX CBTFX_init(&blockLand_SFX[0])
extern const unsigned char blockLand_SFX[];
#endif