/*

	block_land_sfx

	Sound Effect File.

	Info:
		Length			:	7
		Bank			:	0
		Priority		:	0
		Channels used	:	Noise channel

	This file was generated by hammer2cbt

*/
#ifndef __block_land_sfx_h_INCLUDE
#define __block_land_sfx_h_INCLUDE
#define block_land_sfx_Length 7
#define block_land_sfx_Bank 0
#define block_land_sfx_CH_Used 15
#define block_land_sfx_Priority 0
#define CBTFX_PLAY_block_land_sfx CBTFX_init(&block_land_sfx[0][0], 7, 0, 15)
extern const unsigned char block_land_sfx[7][CBTFX_LENGTH];
#endif