/*

		blockRotate_SFX

		Sound Effect File.
		
		Info:
			Length			:	2
			Priority		:	0
			Channels used	:	Duty channel 2
		
		This file was generated by hammer2cbt

	*/
#pragma bank 5
	const unsigned char blockRotate_SFX[] = {
192, // Header
2,
0, 34, 64, 112, 45, 135, 0, 34, 64, 112, 115, 135
};