/*

		blockRotate_SFX

		Sound Effect File.
		
		Info:
			Length			:	2
			Priority		:	0
			Channels used	:	Duty channel 2
		
		This file was generated by hammer2cbt

	*/
	#ifndef __blockRotate_SFX_h_INCLUDE
#define __blockRotate_SFX_h_INCLUDE
#define CBTFX_PLAY_blockRotate_SFX CBTFX_init(&blockRotate_SFX[0])
extern const unsigned char blockRotate_SFX[];
#endif