/*

		SFX_01

		Sound Effect File.
		
		Info:
			Length			:	6
			Priority		:	0
			Channels used	:	Noise channel
		
		This file was generated by hammer2cbt

	*/
#pragma bank 5
	const unsigned char SFX_01[] = {
48, // Header
6,
0, 136, 15, 98, 0, 136, 13, 65, 0, 136, 11, 98, 2, 136, 7, 98, 1, 136, 3, 98, 0, 136, 1, 98
};