/*

		bop_SFX

		Sound Effect File.
		
		Info:
			Length			:	3
			Priority		:	0
			Channels used	:	Duty channel 2
		
		This file was generated by hammer2cbt

	*/
	#ifndef __bop_SFX_h_INCLUDE
#define __bop_SFX_h_INCLUDE
#define CBTFX_PLAY_bop_SFX CBTFX_init(&bop_SFX[0])
extern const unsigned char bop_SFX[];
#endif