/*

	bop_sfx

	Sound Effect File.

	Info:
		Length			:	4
		Bank			:	0
		Priority		:	0
		Channels used	:	Duty channel 2

	This file was generated by hammer2cbt

*/
#ifndef __bop_sfx_h_INCLUDE
#define __bop_sfx_h_INCLUDE
#define bop_sfx_Length 4
#define bop_sfx_Bank 0
#define bop_sfx_CH_Used 240
#define bop_sfx_Priority 0
#define CBTFX_PLAY_bop_sfx CBTFX_init(&bop_sfx[0][0], 4, 0, 240)
extern const unsigned char bop_sfx[4][CBTFX_LENGTH];
#endif