/*

	level_up_4_sfx

	Sound Effect File.

	Info:
		Length			:	14
		Bank			:	0
		Priority		:	0
		Channels used	:	Duty channel 2 & Noise channel

	This file was generated by hammer2cbt

*/
#pragma bank 5
#define level_up_4_sfx_Length 14
#define level_up_4_sfx_Bank 0
#define level_up_4_sfx_CH_Used 255
#define level_up_4_sfx_Priority 0
#define CBTFX_PLAY_level_up_4_sfx CBTFX_init(&level_up_4_sfx[0][0], 14, 0, 255)
#include "cbtfx.h"

const unsigned char level_up_4_sfx[14][CBTFX_LENGTH] = {
	CBTFX_FRAME(2, 17, 15, 0, FX_As2, 17, 10, 96),
	CBTFX_FRAME(4, 17, 14, 1, FX_D_3, 17, 6, 96),
	CBTFX_FRAME(2, 17, 11, 2, FX_F_3, 17, 5, 96),
	CBTFX_FRAME(4, 17, 8, 1, FX_As2, 17, 5, 96),
	CBTFX_FRAME(2, 17, 5, 0, FX_D_3, 17, 4, 96),
	CBTFX_FRAME(4, 17, 3, 1, FX_F_3, 17, 3, 96),
	CBTFX_FRAME(2, 17, 3, 2, FX_As2, 17, 10, 32),
	CBTFX_FRAME(4, 17, 2, 1, FX_D_3, 17, 8, 32),
	CBTFX_FRAME(4, 17, 1, 0, FX_F_3, 17, 2, 32),
	CBTFX_FRAME(1, 17, 0, 1, FX_As2, 17, 0, 0),
	CBTFX_FRAME(2, 17, 3, 2, FX_D_3, 17, 5, 32),
	CBTFX_FRAME(4, 17, 1, 1, FX_F_3, 17, 2, 32),
	CBTFX_FRAME(4, 17, 0, 0, FX_As2, 17, 1, 32)
};