/*

		levelUp4_SFX

		Sound Effect File.
		
		Info:
			Length			:	13
			Priority		:	0
			Channels used	:	Duty channel 2 & Noise channel
		
		This file was generated by hammer2cbt

	*/
#pragma bank 5
	const unsigned char levelUp4_SFX[] = {
240, // Header
13,
1, 170, 0, 250, 231, 134, 96, 3, 170, 64, 230, 33, 135, 96, 1, 170, 128, 181, 68, 135, 96, 3, 170, 64, 133, 231, 134, 96, 1, 170, 0, 84, 33, 135, 96, 3, 170, 64, 51, 68, 135, 96, 1, 170, 128, 58, 231, 134, 32, 3, 170, 64, 40, 33, 135, 32, 3, 170, 0, 18, 68, 135, 32, 0, 170, 64, 0, 231, 134, 0, 1, 170, 128, 53, 33, 135, 32, 3, 170, 64, 18, 68, 135, 32, 3, 170, 0, 1, 231, 134, 32
};