/*

	level_up_sfx

	Sound Effect File.

	Info:
		Length			:	14
		Bank			:	0
		Priority		:	0
		Channels used	:	Duty channel 2 & Noise channel

	This file was generated by hammer2cbt

*/
#pragma bank 5
#define level_up_sfx_Length 14
#define level_up_sfx_Bank 0
#define level_up_sfx_CH_Used 255
#define level_up_sfx_Priority 0
#define CBTFX_PLAY_level_up_sfx CBTFX_init(&level_up_sfx[0][0], 14, 0, 255)
#include "cbtfx.h"

const unsigned char level_up_sfx[14][CBTFX_LENGTH] = {
	CBTFX_FRAME(2, 17, 15, 0, FX_C_4, 17, 10, 96),
	CBTFX_FRAME(4, 17, 10, 0, FX_C_4, 17, 6, 96),
	CBTFX_FRAME(2, 17, 15, 0, FX_D_4, 17, 5, 96),
	CBTFX_FRAME(4, 17, 10, 0, FX_D_4, 17, 5, 96),
	CBTFX_FRAME(2, 17, 15, 0, FX_E_4, 17, 4, 96),
	CBTFX_FRAME(4, 17, 10, 0, FX_E_4, 17, 3, 96),
	CBTFX_FRAME(2, 17, 15, 0, FX_C_5, 17, 10, 32),
	CBTFX_FRAME(4, 17, 10, 0, FX_C_5, 17, 8, 32),
	CBTFX_FRAME(4, 17, 8, 0, FX_C_5, 17, 2, 32),
	CBTFX_FRAME(1, 17, 0, 0, FX_C_0, 17, 0, 0),
	CBTFX_FRAME(2, 17, 2, 0, FX_C_5, 17, 5, 32),
	CBTFX_FRAME(4, 17, 1, 0, FX_C_5, 17, 2, 32),
	CBTFX_FRAME(4, 17, 1, 0, FX_C_5, 17, 1, 32)
};