/*

		levelUp_SFX

		Sound Effect File.
		
		Info:
			Length			:	13
			Priority		:	0
			Channels used	:	Duty channel 2 & Noise channel
		
		This file was generated by hammer2cbt

	*/
	#ifndef __levelUp_SFX_h_INCLUDE
#define __levelUp_SFX_h_INCLUDE
#define CBTFX_PLAY_levelUp_SFX CBTFX_init(&levelUp_SFX[0])
extern const unsigned char levelUp_SFX[];
#endif