/*

		levelUp_SFX

		Sound Effect File.
		
		Info:
			Length			:	13
			Priority		:	0
			Channels used	:	Duty channel 2 & Noise channel
		
		This file was generated by hammer2cbt

	*/
#pragma bank 5
	const unsigned char levelUp_SFX[] = {
240, // Header
13,
1, 170, 0, 250, 131, 135, 96, 3, 170, 0, 166, 131, 135, 96, 1, 170, 0, 245, 144, 135, 96, 3, 170, 0, 165, 144, 135, 96, 1, 170, 0, 244, 157, 135, 96, 3, 170, 0, 163, 157, 135, 96, 1, 170, 0, 250, 193, 135, 32, 3, 170, 0, 168, 193, 135, 32, 3, 170, 0, 130, 193, 135, 32, 0, 170, 0, 0, 44, 128, 0, 1, 170, 0, 37, 193, 135, 32, 3, 170, 0, 18, 193, 135, 32, 3, 170, 0, 17, 193, 135, 32
};