/*

	level_up_sfx

	Sound Effect File.

	Info:
		Length			:	14
		Bank			:	0
		Priority		:	0
		Channels used	:	Duty channel 2 & Noise channel

	This file was generated by hammer2cbt

*/
#ifndef __level_up_sfx_h_INCLUDE
#define __level_up_sfx_h_INCLUDE
#define level_up_sfx_Length 14
#define level_up_sfx_Bank 0
#define level_up_sfx_CH_Used 255
#define level_up_sfx_Priority 0
#define CBTFX_PLAY_level_up_sfx CBTFX_init(&level_up_sfx[0][0], 14, 0, 255)
extern const unsigned char level_up_sfx[14][CBTFX_LENGTH];
#endif