/*

	multi_row_destroyed_sfx

	Sound Effect File.

	Info:
		Length			:	27
		Bank			:	0
		Priority		:	0
		Channels used	:	Duty channel 2 & Noise channel

	This file was generated by hammer2cbt

*/
#pragma bank 5

#define multi_row_destroyed_sfx_Length 27
#define multi_row_destroyed_sfx_Bank 0
#define multi_row_destroyed_sfx_CH_Used 255
#define multi_row_destroyed_sfx_Priority 0
#define CBTFX_PLAY_multi_row_destroyed_sfx CBTFX_init(&multi_row_destroyed_sfx[0][0], 27, 0, 255)
#include "cbtfx.h"

const unsigned char multi_row_destroyed_sfx[27][CBTFX_LENGTH] = {
	CBTFX_FRAME(2, 17, 15, 2, FX_G_2, 17, 15, 241),
	CBTFX_FRAME(2, 17, 13, 2, FX_G_3, 17, 13, 65),
	CBTFX_FRAME(2, 17, 11, 2, FX_A_2, 17, 7, 81),
	CBTFX_FRAME(2, 17, 9, 2, FX_A_3, 17, 6, 81),
	CBTFX_FRAME(2, 17, 7, 2, FX_B_2, 17, 6, 81),
	CBTFX_FRAME(2, 17, 6, 2, FX_B_3, 17, 5, 81),
	CBTFX_FRAME(2, 17, 15, 2, FX_A_2, 17, 5, 81),
	CBTFX_FRAME(2, 17, 13, 2, FX_A_3, 17, 4, 81),
	CBTFX_FRAME(2, 17, 11, 2, FX_B_2, 17, 4, 81),
	CBTFX_FRAME(2, 17, 9, 2, FX_B_3, 17, 3, 81),
	CBTFX_FRAME(2, 17, 7, 2, FX_Cs3, 17, 3, 81),
	CBTFX_FRAME(2, 17, 6, 2, FX_Cs4, 17, 2, 81),
	CBTFX_FRAME(2, 17, 15, 2, FX_B_2, 17, 2, 81),
	CBTFX_FRAME(2, 17, 13, 2, FX_B_3, 17, 1, 81),
	CBTFX_FRAME(2, 17, 11, 2, FX_Cs3, 17, 1, 81),
	CBTFX_FRAME(2, 17, 9, 2, FX_Cs4, 17, 1, 81),
	CBTFX_FRAME(2, 17, 7, 2, FX_Ds3, 17, 1, 81),
	CBTFX_FRAME(2, 17, 6, 2, FX_Ds4, 17, 1, 81),
	CBTFX_FRAME(4, 17, 8, 2, FX_C_5, 0, 0, 0),
	CBTFX_FRAME(1, 17, 6, 2, FX_B_4, 0, 0, 0),
	CBTFX_FRAME(1, 17, 4, 2, FX_A_4, 0, 0, 0),
	CBTFX_FRAME(1, 17, 3, 2, FX_Fs4, 0, 0, 0),
	CBTFX_FRAME(1, 17, 2, 2, FX_E_4, 0, 0, 0),
	CBTFX_FRAME(1, 17, 1, 2, FX_D_4, 0, 0, 0),
	CBTFX_FRAME(5, 17, 2, 2, FX_C_5, 0, 0, 0),
	CBTFX_FRAME(5, 17, 1, 2, FX_C_5, 0, 0, 0)
};