/*

		multiRowDestroyed_SFX

		Sound Effect File.
		
		Info:
			Length			:	26
			Priority		:	0
			Channels used	:	Duty channel 2 & Noise channel
		
		This file was generated by hammer2cbt

	*/
	#ifndef __multiRowDestroyed_SFX_h_INCLUDE
#define __multiRowDestroyed_SFX_h_INCLUDE
#define CBTFX_PLAY_multiRowDestroyed_SFX CBTFX_init(&multiRowDestroyed_SFX[0])
extern const unsigned char multiRowDestroyed_SFX[];
#endif