/*

	multi_row_destroyed_sfx

	Sound Effect File.

	Info:
		Length			:	27
		Bank			:	0
		Priority		:	0
		Channels used	:	Duty channel 2 & Noise channel

	This file was generated by hammer2cbt

*/
#ifndef __multi_row_destroyed_sfx_h_INCLUDE
#define __multi_row_destroyed_sfx_h_INCLUDE
#define multi_row_destroyed_sfx_Length 27
#define multi_row_destroyed_sfx_Bank 0
#define multi_row_destroyed_sfx_CH_Used 255
#define multi_row_destroyed_sfx_Priority 0
#define CBTFX_PLAY_multi_row_destroyed_sfx CBTFX_init(&multi_row_destroyed_sfx[0][0], 27, 0, 255)
extern const unsigned char multi_row_destroyed_sfx[27][CBTFX_LENGTH];
#endif