/*

	row_destroyed_sfx

	Sound Effect File.

	Info:
		Length			:	11
		Bank			:	0
		Priority		:	0
		Channels used	:	Duty channel 2 & Noise channel

	This file was generated by hammer2cbt

*/
#ifndef __row_destroyed_sfx_h_INCLUDE
#define __row_destroyed_sfx_h_INCLUDE
#define row_destroyed_sfx_Length 11
#define row_destroyed_sfx_Bank 0
#define row_destroyed_sfx_CH_Used 255
#define row_destroyed_sfx_Priority 0
#define CBTFX_PLAY_row_destroyed_sfx CBTFX_init(&row_destroyed_sfx[0][0], 11, 0, 255)
extern const unsigned char row_destroyed_sfx[11][CBTFX_LENGTH];
#endif