/*

	row_destroyed_sfx

	Sound Effect File.

	Info:
		Length			:	11
		Bank			:	0
		Priority		:	0
		Channels used	:	Duty channel 2 & Noise channel

	This file was generated by hammer2cbt

*/
#pragma bank 5
#define row_destroyed_sfx_Length 11
#define row_destroyed_sfx_Bank 0
#define row_destroyed_sfx_CH_Used 255
#define row_destroyed_sfx_Priority 0
#define CBTFX_PLAY_row_destroyed_sfx CBTFX_init(&row_destroyed_sfx[0][0], 11, 0, 255)
#include "cbtfx.h"

const unsigned char row_destroyed_sfx[11][CBTFX_LENGTH] = {
	CBTFX_FRAME(2, 17, 15, 2, FX_E_2, 17, 15, 241),
	CBTFX_FRAME(2, 17, 13, 2, FX_E_3, 17, 13, 65),
	CBTFX_FRAME(2, 17, 12, 2, FX_Fs2, 17, 9, 82),
	CBTFX_FRAME(2, 17, 10, 2, FX_Fs3, 17, 7, 82),
	CBTFX_FRAME(2, 17, 9, 2, FX_Gs2, 17, 6, 82),
	CBTFX_FRAME(2, 17, 7, 2, FX_Gs3, 17, 3, 82),
	CBTFX_FRAME(2, 17, 6, 2, FX_As2, 17, 2, 82),
	CBTFX_FRAME(2, 17, 4, 2, FX_As3, 17, 1, 82),
	CBTFX_FRAME(2, 17, 3, 2, FX_C_3, 0, 0, 0),
	CBTFX_FRAME(2, 17, 2, 2, FX_C_4, 0, 0, 0)
};