/*

		rowDestroyed_SFX

		Sound Effect File.
		
		Info:
			Length			:	10
			Priority		:	0
			Channels used	:	Duty channel 2 & Noise channel
		
		This file was generated by hammer2cbt

	*/
	#ifndef __rowDestroyed_SFX_h_INCLUDE
#define __rowDestroyed_SFX_h_INCLUDE
#define CBTFX_PLAY_rowDestroyed_SFX CBTFX_init(&rowDestroyed_SFX[0])
extern const unsigned char rowDestroyed_SFX[];
#endif