/*

		SFX_02

		Sound Effect File.
		
		Info:
			Length			:	10
			Priority		:	0
			Channels used	:	Duty channel 2 & Noise channel
		
		This file was generated by hammer2cbt

	*/
#pragma bank 5
	const unsigned char SFX_02[] = {
240, // Header
10,
1, 170, 128, 255, 114, 134, 98, 1, 170, 128, 221, 57, 135, 65, 1, 170, 128, 201, 158, 134, 82, 1, 170, 128, 167, 79, 135, 82, 1, 170, 128, 150, 196, 134, 82, 1, 170, 128, 115, 98, 135, 82, 1, 170, 128, 98, 231, 134, 82, 1, 170, 128, 65, 115, 135, 82, 1, 34, 128, 48, 6, 135, 0, 1, 34, 128, 32, 131, 135, 0
};