/*

		SFX_0A

		Sound Effect File.
		
		Info:
			Length			:	15
			Priority		:	0
			Channels used	:	Duty channel 2
		
		This file was generated by hammer2cbt

	*/
	#ifndef __SFX_0A_h_INCLUDE
#define __SFX_0A_h_INCLUDE
#define CBTFX_PLAY_SFX_0A CBTFX_init(&SFX_0A[0])
extern const unsigned char SFX_0A[];
#endif