/*

		SFX_0B

		Sound Effect File.
		
		Info:
			Length			:	15
			Priority		:	0
			Channels used	:	Duty channel 2
		
		This file was generated by hammer2cbt

	*/
	#ifndef __SFX_0B_h_INCLUDE
#define __SFX_0B_h_INCLUDE
#define CBTFX_PLAY_SFX_0B CBTFX_init(&SFX_0B[0])
extern const unsigned char SFX_0B[];
#endif