/*

		SFX_0D

		Sound Effect File.
		
		Info:
			Length			:	18
			Priority		:	1
			Channels used	:	Noise channel
		
		This file was generated by hammer2cbt

	*/
#pragma bank 5
	const unsigned char SFX_0D[] = {
49, // Header
18,
1, 136, 15, 241, 0, 136, 13, 49, 0, 136, 11, 98, 2, 136, 7, 98, 1, 136, 3, 98, 0, 136, 1, 97, 1, 136, 8, 241, 0, 136, 6, 49, 0, 136, 5, 98, 2, 136, 3, 98, 0, 136, 2, 98, 1, 136, 1, 97, 1, 136, 4, 241, 0, 136, 3, 49, 0, 136, 2, 98, 2, 136, 1, 98, 0, 136, 1, 98, 1, 136, 1, 97
};