/*

	start_game_sfx

	Sound Effect File.

	Info:
		Length			:	20
		Bank			:	0
		Priority		:	0
		Channels used	:	Duty channel 2 & Noise channel

	This file was generated by hammer2cbt

*/
#ifndef __start_game_sfx_h_INCLUDE
#define __start_game_sfx_h_INCLUDE
#define start_game_sfx_Length 20
#define start_game_sfx_Bank 0
#define start_game_sfx_CH_Used 255
#define start_game_sfx_Priority 0
#define CBTFX_PLAY_start_game_sfx CBTFX_init(&start_game_sfx[0][0], 20, 0, 255)
extern const unsigned char start_game_sfx[20][CBTFX_LENGTH];
#endif