/*

		startGame_SFX

		Sound Effect File.
		
		Info:
			Length			:	19
			Priority		:	0
			Channels used	:	Duty channel 2 & Noise channel
		
		This file was generated by hammer2cbt

	*/
	#ifndef __startGame_SFX_h_INCLUDE
#define __startGame_SFX_h_INCLUDE
#define CBTFX_PLAY_startGame_SFX CBTFX_init(&startGame_SFX[0])
extern const unsigned char startGame_SFX[];
#endif