/*

	start_game_sfx

	Sound Effect File.

	Info:
		Length			:	20
		Bank			:	0
		Priority		:	0
		Channels used	:	Duty channel 2 & Noise channel

	This file was generated by hammer2cbt

*/
#pragma bank 5
#define start_game_sfx_Length 20
#define start_game_sfx_Bank 0
#define start_game_sfx_CH_Used 255
#define start_game_sfx_Priority 0
#define CBTFX_PLAY_start_game_sfx CBTFX_init(&start_game_sfx[0][0], 20, 0, 255)
#include "cbtfx.h"

const unsigned char start_game_sfx[20][CBTFX_LENGTH] = {
	CBTFX_FRAME(3, 17, 15, 1, FX_C_4, 17, 5, 32),
	CBTFX_FRAME(3, 17, 8, 1, FX_C_4, 17, 2, 32),
	CBTFX_FRAME(3, 17, 15, 1, FX_G_3, 17, 5, 48),
	CBTFX_FRAME(3, 17, 8, 1, FX_G_3, 17, 2, 48),
	CBTFX_FRAME(3, 17, 15, 1, FX_As3, 17, 5, 64),
	CBTFX_FRAME(3, 17, 8, 1, FX_As3, 17, 2, 64),
	CBTFX_FRAME(3, 17, 15, 1, FX_D_4, 17, 5, 80),
	CBTFX_FRAME(3, 17, 8, 1, FX_D_4, 17, 2, 80),
	CBTFX_FRAME(3, 17, 15, 1, FX_G_4, 17, 5, 81),
	CBTFX_FRAME(3, 17, 8, 1, FX_G_4, 17, 2, 81),
	CBTFX_FRAME(3, 17, 4, 1, FX_G_4, 17, 1, 81),
	CBTFX_FRAME(3, 17, 2, 1, FX_G_4, 17, 1, 81),
	CBTFX_FRAME(3, 17, 2, 1, FX_G_4, 17, 1, 81),
	CBTFX_FRAME(3, 17, 1, 1, FX_G_4, 17, 1, 81),
	CBTFX_FRAME(3, 17, 1, 1, FX_G_4, 17, 1, 81),
	CBTFX_FRAME(3, 17, 1, 1, FX_G_4, 17, 1, 81),
	CBTFX_FRAME(3, 17, 1, 1, FX_G_4, 17, 1, 81),
	CBTFX_FRAME(3, 17, 1, 1, FX_G_4, 17, 1, 81),
	CBTFX_FRAME(3, 17, 1, 1, FX_G_4, 17, 1, 81)
};