/*

	unable_rotate_sfx

	Sound Effect File.

	Info:
		Length			:	3
		Bank			:	0
		Priority		:	0
		Channels used	:	Duty channel 2

	This file was generated by hammer2cbt

*/
#pragma bank 5
#define unable_rotate_sfx_Length 3
#define unable_rotate_sfx_Bank 0
#define unable_rotate_sfx_CH_Used 240
#define unable_rotate_sfx_Priority 0
#define CBTFX_PLAY_unable_rotate_sfx CBTFX_init(&unable_rotate_sfx[0][0], 3, 0, 240)
#include "cbtfx.h"

const unsigned char unable_rotate_sfx[3][CBTFX_LENGTH] = {
	CBTFX_FRAME(1, 17, 10, 2, FX_B_1, 0, 0, 0),
	CBTFX_FRAME(1, 17, 10, 2, FX_E_1, 0, 0, 0)
};