/*

		unableRotate_SFX

		Sound Effect File.
		
		Info:
			Length			:	2
			Priority		:	0
			Channels used	:	Duty channel 2
		
		This file was generated by hammer2cbt

	*/
#pragma bank 5
	const unsigned char unableRotate_SFX[] = {
192, // Header
2,
0, 34, 128, 160, 237, 133, 0, 34, 128, 160, 229, 132
};