/*

		unableRotate_SFX

		Sound Effect File.
		
		Info:
			Length			:	2
			Priority		:	0
			Channels used	:	Duty channel 2
		
		This file was generated by hammer2cbt

	*/
	#ifndef __unableRotate_SFX_h_INCLUDE
#define __unableRotate_SFX_h_INCLUDE
#define CBTFX_PLAY_unableRotate_SFX CBTFX_init(&unableRotate_SFX[0])
extern const unsigned char unableRotate_SFX[];
#endif